### Broadcasting

Some examples of broadcasting

In [2]:
import numpy as np

In [3]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [5]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [9]:
percentage = 100*A/cal.reshape(1, 4)

print(cal.reshape(1, 4))
print(percentage)

[[ 59.  239.  155.4  76.9]]
[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


By adding a $(1, n)$ vector to an $(m, n)$ matrix, numpy automatically converts (broadcasts) the $(1, n)$ vector into an $(m, n)$ matrix consisting of multiple rows of the vector.

In [18]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
c

array([[ 0.07670586, -0.04350997,  0.00318594],
       [ 0.07609659, -0.05703403, -0.79639128],
       [ 0.10241791, -0.21665938,  0.19747066]])